import { registerHelloTool } from "./hello.js";
import { registerListCompaniesTool } from "./list-companies.js";
import { registerListCustomersTool } from "./list-customers.js";
import { registerCreateInvoiceDraftTool } from "./create-invoice-draft.js";
import { registerUpdateInvoiceDraftTool } from "./update-invoice-draft.js";
import { registerUpdateCustomerTool } from "./update-customer.js";
import { registerGetCustomerTool } from "./get-customer.js";
import { registerListProductsTool } from "./list-products.js";
import { registerUpsertProductTool } from "./upsert-product.js";
import { registerListInvoiceDraftsTool } from "./list-invoice-drafts.js";
import { registerGetInvoiceDraftTool } from "./get-invoice-draft.js";
import { registerBookInvoiceDraftTool } from "./book-invoice-draft.js";
import { registerListBookedInvoicesTool } from "./list-booked-invoices.js";
import { registerGetBookedInvoiceTool } from "./get-booked-invoice.js";
import { registerDownloadInvoicePdfTool } from "./download-invoice-pdf.js";
import { registerListPaymentTermsTool } from "./list-payment-terms.js";
import { registerListCustomerGroupsTool } from "./list-customer-groups.js";
import { registerListVatZonesTool } from "./list-vat-zones.js";
import { registerListAccountingYearsTool } from "./list-accounting-years.js";
import { registerListAccountsTool } from "./list-accounts.js";
import { registerListVatAccountsTool } from "./list-vat-accounts.js";
import { registerListJournalsTool } from "./list-journals.js";
import { registerListBookedEntriesTool } from "./list-booked-entries.js";
import { registerListAccountEntriesTool } from "./list-account-entries.js";
import { registerListAccountTotalsTool } from "./list-account-totals.js";
import { registerListJournalDraftEntriesTool } from "./list-journal-draft-entries.js";

const registerTools = (server) => {
  registerHelloTool(server);
  registerListCompaniesTool(server);
  registerListCustomersTool(server);
  registerGetCustomerTool(server);
  registerListProductsTool(server);
  registerUpsertProductTool(server);
  registerCreateInvoiceDraftTool(server);
  registerUpdateInvoiceDraftTool(server);
  registerUpdateCustomerTool(server);
  registerListInvoiceDraftsTool(server);
  registerGetInvoiceDraftTool(server);
  registerBookInvoiceDraftTool(server);
  registerListBookedInvoicesTool(server);
  registerGetBookedInvoiceTool(server);
  registerDownloadInvoicePdfTool(server);
  registerListPaymentTermsTool(server);
  registerListCustomerGroupsTool(server);
  registerListVatZonesTool(server);
  registerListAccountingYearsTool(server);
  registerListAccountsTool(server);
  registerListVatAccountsTool(server);
  registerListJournalsTool(server);
  registerListBookedEntriesTool(server);
  registerListAccountEntriesTool(server);
  registerListAccountTotalsTool(server);
  registerListJournalDraftEntriesTool(server);
};

export default registerTools;
